routes/web.php
<?php

// Front end routes

Route::get('/', ['uses' => 'Web\BlogController@index', 'as' => 'blog.index'] );
Route::get('/article/{slug}', ['uses' => 'Web\BlogController@detail', 'as' => 'blog.detail'] );

Route::get('/about', function() { return redirect('/about/netrunner'); });
Route::get('/about/netrunner', function () { return view('pages/about/netrunner'); });
Route::get('/about/nisei', function () { return view('pages/about/nisei'); });
Route::get('/about/code-of-conduct', function () { return view('pages/about/code-of-conduct'); });
Route::get('/about/faqs', function () { return view('pages/about/faqs'); });

Route::get('/op', function() { return redirect('/op/available-kits'); });
Route::get('/op/supported-formats', function() { return view('pages/op/formats'); });
Route::get('/op/available-kits', ['uses' => 'Web\OPController@indexForStores', 'as' => 'op.storeIndex'] );
Route::get('/op/available-kits/{slug}', ['uses' => 'Web\OPController@detailForStores', 'as' => 'op.storeEvent'] );
Route::get('/op/resources', function () { return view('pages/op/resources'); });

Route::post('paypal', array('as' => 'paypal','uses' => 'Web\PaypalController@postPaymentWithpaypal',));
Route::get('paypal', array('as' => 'status','uses' => 'Web\PaypalController@getPaymentStatus',));

// RSS feed route

Route::feeds();

// Admin routes

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/', function() { return redirect('/admin/home'); });
    Route::get('/home', 'HomeController@index');
    
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);

    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);

    Route::resource('blogs', 'Admin\BlogsController');
    Route::post('blogs_mass_destroy', ['uses' => 'Admin\BlogsController@massDestroy', 'as' => 'blogs.mass_destroy']);
    Route::post('blogs_restore/{id}', ['uses' => 'Admin\BlogsController@restore', 'as' => 'blogs.restore']);
    Route::delete('blogs_perma_del/{id}', ['uses' => 'Admin\BlogsController@perma_del', 'as' => 'blogs.perma_del']);

    Route::resource('categories', 'Admin\CategoriesController');
    Route::post('categories_mass_destroy', ['uses' => 'Admin\CategoriesController@massDestroy', 'as' => 'categories.mass_destroy']);

    Route::resource('faqs', 'Admin\FAQsController');
    Route::post('faqs_mass_destroy', ['uses' => 'Admin\FAQsController@massDestroy', 'as' => 'faqs.mass_destroy']);

    Route::resource('events', 'Admin\EventsController');
    Route::post('events_mass_destroy', ['uses' => 'Admin\EventsController@massDestroy', 'as' => 'events.mass_destroy']);
    Route::post('events_restore/{id}', ['uses' => 'Admin\EventsController@restore', 'as' => 'events.restore']);
    Route::delete('events_perma_del/{id}', ['uses' => 'Admin\EventsController@perma_del', 'as' => 'events.perma_del']);



 
});

app/Faq.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Faq
 *
 * @package App
 * @property string $question
 * @property text $answer
*/
class Faq extends Model
{
    protected $fillable = ['question', 'answer'];
    protected $hidden = [];

}

app/Http/Controllers/Admin/FAQsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Faq;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreFAQsRequest;
use App\Http\Requests\Admin\UpdateFAQsRequest;

class FaqsController extends Controller
{
    /**
     * Display a listing of Faqs
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('faqs_access')) {
            return abort(401);
        }

        if (request('show_deleted') == 1) {
            if (! Gate::allows('faqs_delete')) {
                return abort(401);
            }
            $faqs = Faq::onlyTrashed()->get();
        } else {
            $faqs = Faq::all();
        }

        return view('admin.faqs.index', compact('faqs'));
    }

    /**
     * Show the form for creating new Faq.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('faqs_create')) {
            return abort(401);
        }

        return view('admin.faqs.create');
    }

    /**
     * Store a newly created Faq in storage.
     *
     * @param  \App\Http\Requests\StoreFAQsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreFAQsRequest $request)
    {
        if (! Gate::allows('faqs_create')) {
            return abort(401);
        }
        $faqs = Faq::create($request->all());



        return redirect()->route('admin.faqs.index');
    }


    /**
     * Show the form for editing Faq.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('faqs_edit')) {
            return abort(401);
        }

        $faq = Faq::findOrFail($id);

        return view('admin.faqs.edit', compact('faq'));
    }

    /**
     * Update Faq in storage.
     *
     * @param  \App\Http\Requests\UpdateFAQsRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateFAQsRequest $request, $id)
    {
        if (! Gate::allows('faqs_edit')) {
            return abort(401);
        }
        $faq = Faq::findOrFail($id);
        $faq->update($request->all());



        return redirect()->route('admin.faqs.index');
    }


    /**
     * Display Faq.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('faqs_view')) {
            return abort(401);
        }
        $faq = Faq::findOrFail($id);

        return view('admin.faqs.show', compact('faq'));
    }


    /**
     * Remove Faq from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('faqs_delete')) {
            return abort(401);
        }
        $faq = Faq::findOrFail($id);
        $faq->delete();

        return redirect()->route('admin.faqs.index');
    }

    /**
     * Delete all selected Faqs at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('faqs_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Faq::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }


    /**
     * Restore Faq from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        if (! Gate::allows('faqs_delete')) {
            return abort(401);
        }
        $faq = Faq::onlyTrashed()->findOrFail($id);
        $faq->restore();

        return redirect()->route('admin.faqs.index');
    }

    /**
     * Permanently delete Faq from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function perma_del($id)
    {
        if (! Gate::allows('faqs_delete')) {
            return abort(401);
        }
        $faq = Faq::onlyTrashed()->findOrFail($id);
        $faq->forceDelete();

        return redirect()->route('admin.faqs.index');
    }
}

resources/views/admin/faqs/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.faqs.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.faqs.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('question', trans('quickadmin.faqs.fields.question').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('question', old('question'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('question'))
                        <p class="help-block">
                            {{ $errors->first('question') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('answer', trans('quickadmin.faqs.fields.answer').'*', ['class' => 'control-label']) !!}
                    {!! Form::textarea('answer', old('answer'), ['class' => 'form-control editor', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('answer'))
                        <p class="help-block">
                            {{ $errors->first('answer') }}
                        </p>
                    @endif
                </div>
            </div>
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

@section('javascript')
    @parent
    <script src="//cdn.ckeditor.com/4.5.4/full/ckeditor.js"></script>
    <script>
        $('.editor').each(function () {
                  CKEDITOR.replace($(this).attr('id'),{
                    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
                    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
                    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
                    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
            });
        });
    </script>
@stop

resources/views/admin/faqs/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.faqs.title')</h3>
    
    {!! Form::model($faq, ['method' => 'PUT', 'route' => ['admin.faqs.update', $faq->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('question', trans('quickadmin.faqs.fields.question').'*', ['class' => 'control-label']) !!}
                    {!! Form::text('question', old('question'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('question'))
                        <p class="help-block">
                            {{ $errors->first('question') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('answer', trans('quickadmin.faqs.fields.answer').'*', ['class' => 'control-label']) !!}
                    {!! Form::textarea('answer', old('answer'), ['class' => 'form-control editor', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('answer'))
                        <p class="help-block">
                            {{ $errors->first('answer') }}
                        </p>
                    @endif
                </div>
            </div>
        </div>
    </div>

    {!! Form::submit(trans('quickadmin.qa_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

@section('javascript')
    @parent
    <script src="//cdn.ckeditor.com/4.5.4/full/ckeditor.js"></script>
    <script>
        $('.editor').each(function () {
                  CKEDITOR.replace($(this).attr('id'),{
                    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
                    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
                    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
                    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
            });
        });
    </script>
@stop

resources/views/admin/faqs/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.faqs.title')</h3>
    @can('faqs_create')
    <p>
        <a href="{{ route('admin.faqs.create') }}" class="btn btn-success">@lang('quickadmin.qa_add_new')</a>
        
    </p>
    @endcan

    

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($faqs) > 0 ? 'datatable' : '' }} @can('faqs_delete') dt-select @endcan">
                <thead>
                    <tr>
                        @can('faqs_delete')
                            <th style="text-align:center;"><input type="checkbox" id="select-all" /></th>
                        @endcan

                        <th>@lang('quickadmin.faqs.fields.question')</th>
                                                <th>&nbsp;</th>

                    </tr>
                </thead>
                
                <tbody>
                    @if (count($faqs) > 0)
                        @foreach ($faqs as $faq)
                            <tr data-entry-id="{{ $faq->id }}">
                                @can('faqs_delete')
                                    <td></td>
                                @endcan

                                <td field-key='title'>{{ $faq->question }}</td>
                                                                <td>
                                    @can('faqs_view')
                                    <a href="{{ route('admin.faqs.show',[$faq->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('faqs_edit')
                                    <a href="{{ route('admin.faqs.edit',[$faq->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('faqs_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.faqs.destroy', $faq->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="6">@lang('quickadmin.qa_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('faqs_delete')
            window.route_mass_crud_entries_destroy = '{{ route('admin.faqs.mass_destroy') }}';
        @endcan

    </script>
@endsection

resources/views/admin/faqs/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.faqs.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.faqs.fields.question')</th>
                            <td field-key='title'>{{ $faq->question }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.faqs.fields.answer')</th>
                            <td field-key='conteanswernt'>{!! $faq->answer !!}</td>
                        </tr>
                    </table>
                </div>
            </div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.faqs.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop